apiVersion: v1
kind: Service
metadata:
  name: hello1
  namespace: hello
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: hello1
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
